pr:
  autoCancel: false
  branches:
    include:
    - '*'

variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.pip

jobs:
- job: lint
  displayName: 'Lint'

  pool:
    vmImage: 'Ubuntu 18.04'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Set Python version'
    inputs:
      versionSpec: '3.8.x'
      addToPath: true

  - task: Cache@2
    inputs:
      key: 'python | "$(Agent.OS)" | poetry.lock'
      restoreKeys: | 
        python | "$(Agent.OS)"
        python
      path: $(PIP_CACHE_DIR)
    displayName: Cache pip packages

  - script: pip install poetry
    displayName: Install Poetry

  - script: poetry config virtualenvs.create false
    displayName: Disable Poetry VirtualEnvs

  - script: poetry install --no-interaction --no-ansi
    displayName: Install project using Poetry

  - script: python -m flake8 .
    displayName: 'Run linter'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '$(System.DefaultWorkingDirectory)/flake8.xml'
      testRunTitle: 'Publish test results from flake8'